# Site settings
title: Alex Windett
job_title: Web Developer
baseurl: ""
url: "http://windett.co.uk"

# Build settings
markdown: kramdown

# Content settings
social:
    - name: Mail
      icon: mail
      username: windettalex@gmail.com
      url: windettalex@gmai.com

    - name: Twitter
      icon: twitter
      username: alexwindett
      url: https://twitter.com/alexwindett

    - name: GitHub
      icon: github
      username: alex-windett
      url: https://github.com/alex-windett
      desc: Fork me on GitHub

    - name: LinkedIn
      icon: linkedin
      username: Alex Windett
      url: https://uk.linkedin.com/in/alexwindett
      desc: Connect with me on LinkedIn

projects:
    - name: 9BAR
      url: https://www.9bar.com
      description: 'Yes+ is a project that Alex worked on, but it was before Big Fish so I don’t vknow anything about it. You should read this paragraph that’s delivering concise information as to what he did and then you should'
    - name: Yes+
      url: https://www.yesplus.org.uk
      description: 'Yes+ is a project that Alex worked on, but it was before Big Fish so I don’t vknow anything about it. You should read this paragraph that’s delivering concise information as to what he did and then you should'
    - name: Tyrrells
      url: https://www.tyrrellscrisps.co.uk
      description: 'Yes+ is a project that Alex worked on, but it was before Big Fish so I don’t vknow anything about it. You should read this paragraph that’s delivering concise information as to what he did and then you should'
    - name: Tyrrells
      url: https://www.tyrrellscrisps.co.uk
      description: 'Yes+ is a project that Alex worked on, but it was before Big Fish so I don’t vknow anything about it. You should read this paragraph that’s delivering concise information as to what he did and then you should'
    - name: Tyrrells
      url: https://www.tyrrellscrisps.co.uk
      description: 'Yes+ is a project that Alex worked on, but it was before Big Fish so I don’t vknow anything about it. You should read this paragraph that’s delivering concise information as to what he did and then you should'