# External gems
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: Alex Windett
subtitle: "London based Full Stack Developer"
email: windettalex@gmail.com
name: Alex Windett
description: London based Full Stack Developer
baseurl: "/" # the subpath of your site, e.g. /blog/
url: http://windett.co.uk
cover: "assets/keyboard.jpg"
logo: "assets/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
ga_tracking_id: "UA-55311551-1"

# Should pages be able to be shared on social sites
post_sharing: false

# Category descriptions (for archive pages)
descriptions:
  - cat: css
    desc: "All things interesting on SASS and CSS"

  - cat: js
    desc: "Wonderful world of JavaScript"

  - cat: other
    desc: "Whats happening in my world"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: Alex Windett
    url: https://twitter.com/alexwindett
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: alex-windett
    url: https://github.com/alex-windett
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Alex Windett
    url: https://uk.linkedin.com/in/alexwindett
    desc: Connect with me on LinkedIn
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"

    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
    os_rcs_type: "git"
    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"

tools:
  - name: Ruby on Rails + Ruby
  - name: Wordpress + PHP
  - name: Grunt + Bower
  - name: CSS Sass + Less
  - name: JavaScript and jQuery
  - name: Photoshop and Illustrator

my_sites:
  - name: 9bar
    image: 9bar.png
    url: http://www.9bar.com

  - name: Yes+
    image: yes+.png
    url: http://www.yesplus.org.uk
site_map: false
rss: false