# Site settings
title: Alex Windett
job_title: UX Designer & Frontend Developer
baseurl: ""
url: "https://windett.co.uk"

# Build settings
markdown: kramdown

# Permalink style
permalink: pretty

# Pagination
paginate: 10
paginate_path: "/blog/page/:num"

exclude: ['css', '_scss']
keep_files: ['_site/css']

gems:
  [jekyll-paginate]

exclude:
  [
    node_modules,
    Gruntfile.js,
    package.json
  ]

include: ['.htaccess']


# Content settings
social:
    - name: Mail
      icon: mail
      username: windettalex@gmail.com
      url: windettalex@gmai.com

    - name: Twitter
      icon: twitter
      username: alexwindett
      url: https://twitter.com/alexwindett

    - name: GitHub
      icon: github
      username: alex-windett
      url: https://github.com/alex-windett
      desc: Fork me on GitHub

    - name: LinkedIn
      icon: linkedin
      username: Alex Windett
      url: https://uk.linkedin.com/in/alexwindett
      desc: Connect with me on LinkedIn

      - name: GitLab
        icon: gitlab
        username: alexw1
        url: https://gitlab.com/alexw1
        desc: Find me on GitLab

projects:
    - name: 'Freddies Flowers'
      url: https://www.freddiesflowers.com
      description: 'A flower delivery e-commerce app being re-built in bi-monthly or weekly sprints - depending on the feature - in React and Redux. Driving the project, it is the first I have used React and a JavaScript framework, bringing about some challanges but has ultimately imporved the UX and functionality.'
    - name: 'Belvoir Botanicals'
      url: http://www.belvoirbotanicals.co.uk/
      description: 'This micro site for an excisting client gave me the opporutnity to use more advanced Sass, include writing my own functions, loops and high level mixins. Producing more concise code I was able to deliver a piece of work in a short space of time and to a high quality.'
    - name: 9BAR
      url: http://www.9bar.com
      description: '9BAR was my first lead role in developing a site. The learning curve whilst working on this project was steep and very rewarding as, not only, were the clients happy with the end result but I aquired many valuable and transferable skills while working on it.'
    - name: Tyrrells
      url: https://www.tyrrellscrisps.co.uk
      description: 'Working on Tyrrells involved inheriting a legacy site with the end result being an imporved code base across it&rsquo;s multiple sites and an upgrade of the outdated components whilst refactoring down templates, styles and JavaScript.'
    - name: Yes+
      description: 'Working on YES+ remotely gave me the expirience of working on a project away from a face to face environment. It also gave me to opportunity to explore new processes whilst also strengthening excisting skills. Due to the short time from, code was frequently deployed for review.'
