# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

social:
  - name: Mail
    icon: mail
    username: windettalex@gmail.com
    url: windettalex@gmai.com

  - name: Twitter
    icon: twitter
    username: alexwindett
    url: https://twitter.com/alexwindett

  - name: GitHub
    icon: github
    username: alex-windett
    url: https://github.com/alex-windett
    desc: Fork me on GitHub

  - name: LinkedIn
    icon: linkedin
    username: Alex Windett
    url: https://uk.linkedin.com/in/alexwindett
    desc: Connect with me on LinkedIn